/* Generated by Yosys 0.13 (git sha1 8b1eafc3a, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module dom_and(Ax, Ay, Bx, By, Z0, clk, rstn, Aq, Bq);
  wire _0_;
  output Aq;
  input Ax;
  input Ay;
  output Bq;
  input Bx;
  input By;
  input Z0;
  wire add_AxAy_AxBy;
  wire add_BxAy_BxBy;
  wire add_BxZ0;
  input clk;
  wire mul_AxAy;
  wire mul_AxBy;
  wire mul_BxAy;
  wire mul_BxBy;
  input rstn;
  assign mul_AxAy = Ax & Ay;
  assign mul_AxBy = Ax & By;
  assign mul_BxAy = Bx & Ay;
  assign mul_BxBy = Bx & By;
  assign add_AxAy_AxBy = mul_AxAy ^ mul_AxBy;
  assign add_BxAy_BxBy = mul_BxAy ^ mul_BxBy;
  assign add_BxZ0 = mul_BxBy ^ Z0;
  assign _0_ = add_BxZ0 ^ add_AxAy_AxBy;
  assign Aq = _0_ ^ add_BxAy_BxBy;
  assign Bq = Z0;
endmodule
