python3  $ALMA_ROOT/verify.py \
    --json circuit.json \
    --label labels.txt \
    --vcd trace.vcd \
    --cycles 32 \
    --mode transient \
    --checking-mode per-secret \
    --rst-name rstn \
    -p 0 \
    -s 2 \
    --probing-model time-constrained \
    --top-module dom_mult
